artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Pascalihub/Project_data/raw/main/stud.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/unzipped_data

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train_data.csv", "test_data.csv", "raw_data.csv", "Flight.csv"]
 
data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/unzipped_data
  preprocessor_path: artifacts/data_transformation/preprocessors.pkl


model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/model_trainer/unzipped_data
  model_path: artifacts/model_trainer/model.pkl

model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/unzipped_data
  model_path: artifacts/model_trainer/model.pkl
  metric_file_name: artifacts/model_evaluation/metrics.csv